// <auto-generated />
using System;
using BookBlastInc.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookBlastInc.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230621122843_AddCategory")]
    partial class AddCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BookBlastInc.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DisplayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BookBlastInc.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8512490-fccb-458c-97df-f0c4d64fa460"),
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("96032cbe-73bf-4706-96b5-93c8ae1ed236"),
                            Name = "Client"
                        },
                        new
                        {
                            Id = new Guid("c3682bc4-02ee-4956-83d3-8fb01289b8c6"),
                            Name = "Employee"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
